// <auto-generated />
using System;
using BurgerAppDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerAppDataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240427054758_nig_1")]
    partial class nig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BurgerAppDomain.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Main St, Anytown, USA",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "(555) 123-4567",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Elm St, Smalltown, USA",
                            Email = "emily.smith@example.com",
                            FirstName = "Emily",
                            LastName = "Smith",
                            PhoneNumber = "(555) 234-5678",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "789 Oak St, Cityville, USA",
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            PhoneNumber = "(555) 345-6789",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "101 Maple Ave, Villagetown, USA",
                            Email = "sarah.williams@example.com",
                            FirstName = "Sarah",
                            LastName = "Williams",
                            PhoneNumber = "(555) 456-7890",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "202 Cedar St, Townsville, USA",
                            Email = "christopher.brown@example.com",
                            FirstName = "Christopher",
                            LastName = "Brown",
                            PhoneNumber = "(555) 567-8901",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "303 Pine St, Hamletville, USA",
                            Email = "jessica.davis@example.com",
                            FirstName = "Jessica",
                            LastName = "Davis",
                            PhoneNumber = "(555) 678-9012",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "404 Birch St, Suburbia, USA",
                            Email = "matthew.miller@example.com",
                            FirstName = "Matthew",
                            LastName = "Miller",
                            PhoneNumber = "(555) 789-0123",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "505 Walnut St, Riverside, USA",
                            Email = "ashley.wilson@example.com",
                            FirstName = "Ashley",
                            LastName = "Wilson",
                            PhoneNumber = "(555) 890-1234",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "606 Oak St, Hillside, USA",
                            Email = "daniel.moore@example.com",
                            FirstName = "Daniel",
                            LastName = "Moore",
                            PhoneNumber = "(555) 901-2345",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "707 Maple St, Lakeside, USA",
                            Email = "amanda.taylor@example.com",
                            FirstName = "Amanda",
                            LastName = "Taylor",
                            PhoneNumber = "(555) 012-3456",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "808 Pine St, Mountainview, USA",
                            Email = "robert.martinez@example.com",
                            FirstName = "Robert",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 123-4567",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "909 Cedar St, Beachtown, USA",
                            Email = "jennifer.hernandez@example.com",
                            FirstName = "Jennifer",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 234-5678",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "111 Birch St, Countryside, USA",
                            Email = "james.lopez@example.com",
                            FirstName = "James",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 345-6789",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "222 Elm St, Riverside, USA",
                            Email = "mary.gonzalez@example.com",
                            FirstName = "Mary",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 456-7890",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "333 Oak St, Suburbia, USA",
                            Email = "david.wilson@example.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            PhoneNumber = "(555) 567-8901",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "444 Maple St, Cityville, USA",
                            Email = "maria.taylor@example.com",
                            FirstName = "Maria",
                            LastName = "Taylor",
                            PhoneNumber = "(555) 678-9012",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "555 Pine St, Hillside, USA",
                            Email = "charles.martinez@example.com",
                            FirstName = "Charles",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 789-0123",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "666 Cedar St, Townsville, USA",
                            Email = "patricia.hernandez@example.com",
                            FirstName = "Patricia",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 890-1234",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "777 Birch St, Lakeside, USA",
                            Email = "richard.lopez@example.com",
                            FirstName = "Richard",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 901-2345",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "888 Elm St, Beachside, USA",
                            Email = "linda.gonzalez@example.com",
                            FirstName = "Linda",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 012-3456",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "999 Pine St, Citytown, USA",
                            Email = "thomas.martinez@example.com",
                            FirstName = "Thomas",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 123-4567",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "101 Oak St, Countryside, USA",
                            Email = "karen.hernandez@example.com",
                            FirstName = "Karen",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 234-5678",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "202 Cedar St, Riverside, USA",
                            Email = "steven.lopez@example.com",
                            FirstName = "Steven",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 345-6789",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "303 Elm St, Suburbia, USA",
                            Email = "barbara.gonzalez@example.com",
                            FirstName = "Barbara",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 456-7890",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "404 Maple St, Hillside, USA",
                            Email = "joseph.taylor@example.com",
                            FirstName = "Joseph",
                            LastName = "Taylor",
                            PhoneNumber = "(555) 567-8901",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "505 Pine St, Lakeside, USA",
                            Email = "donna.martinez@example.com",
                            FirstName = "Donna",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 678-9012",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "606 Oak St, Beachside, USA",
                            Email = "ronald.hernandez@example.com",
                            FirstName = "Ronald",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 789-0123",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "707 Cedar St, Smalltown, USA",
                            Email = "laura.lopez@example.com",
                            FirstName = "Laura",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 890-1234",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "808 Elm St, Mountainview, USA",
                            Email = "kenneth.gonzalez@example.com",
                            FirstName = "Kenneth",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 901-2345",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "909 Oak St, Beachtown, USA",
                            Email = "margaret.wilson@example.com",
                            FirstName = "Margaret",
                            LastName = "Wilson",
                            PhoneNumber = "(555) 012-3456",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 31,
                            Address = "101 Maple Ave, Cityville, USA",
                            Email = "karen.martinez@example.com",
                            FirstName = "Karen",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 123-4567",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 32,
                            Address = "202 Cedar St, Townsville, USA",
                            Email = "anthony.hernandez@example.com",
                            FirstName = "Anthony",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 234-5678",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 33,
                            Address = "303 Elm St, Hillside, USA",
                            Email = "sharon.lopez@example.com",
                            FirstName = "Sharon",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 345-6789",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 34,
                            Address = "404 Pine St, Countryside, USA",
                            Email = "gary.gonzalez@example.com",
                            FirstName = "Gary",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 456-7890",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 35,
                            Address = "505 Cedar St, Riverside, USA",
                            Email = "deborah.taylor@example.com",
                            FirstName = "Deborah",
                            LastName = "Taylor",
                            PhoneNumber = "(555) 567-8901",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 36,
                            Address = "606 Oak St, Suburbia, USA",
                            Email = "edward.martinez@example.com",
                            FirstName = "Edward",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 678-9012",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 37,
                            Address = "707 Elm St, Lakeside, USA",
                            Email = "kimberly.hernandez@example.com",
                            FirstName = "Kimberly",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 789-0123",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 38,
                            Address = "808 Cedar St, Beachside, USA",
                            Email = "steven.lopez@example.com",
                            FirstName = "Steven",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 890-1234",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 39,
                            Address = "909 Elm St, Mountainview, USA",
                            Email = "susan.gonzalez@example.com",
                            FirstName = "Susan",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 901-2345",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 40,
                            Address = "101 Pine St, Beachtown, USA",
                            Email = "brian.wilson@example.com",
                            FirstName = "Brian",
                            LastName = "Wilson",
                            PhoneNumber = "(555) 012-3456",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 41,
                            Address = "202 Maple Ave, Cityville, USA",
                            Email = "elizabeth.martinez@example.com",
                            FirstName = "Elizabeth",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 123-4567",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 42,
                            Address = "303 Oak St, Townsville, USA",
                            Email = "charles.hernandez@example.com",
                            FirstName = "Charles",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 234-5678",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 43,
                            Address = "404 Elm St, Hillside, USA",
                            Email = "donna.lopez@example.com",
                            FirstName = "Donna",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 345-6789",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 44,
                            Address = "505 Cedar St, Countryside, USA",
                            Email = "david.gonzalez@example.com",
                            FirstName = "David",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 456-7890",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 45,
                            Address = "606 Maple St, Riverside, USA",
                            Email = "jennifer.taylor@example.com",
                            FirstName = "Jennifer",
                            LastName = "Taylor",
                            PhoneNumber = "(555) 567-8901",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 46,
                            Address = "707 Elm St, Suburbia, USA",
                            Email = "michael.martinez@example.com",
                            FirstName = "Michael",
                            LastName = "Martinez",
                            PhoneNumber = "(555) 678-9012",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 47,
                            Address = "808 Pine St, Lakeside, USA",
                            Email = "barbara.hernandez@example.com",
                            FirstName = "Barbara",
                            LastName = "Hernandez",
                            PhoneNumber = "(555) 789-0123",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 48,
                            Address = "909 Oak St, Beachside, USA",
                            Email = "john.lopez@example.com",
                            FirstName = "John",
                            LastName = "Lopez",
                            PhoneNumber = "(555) 890-1234",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 49,
                            Address = "101 Cedar St, Mountainview, USA",
                            Email = "jessica.gonzalez@example.com",
                            FirstName = "Jessica",
                            LastName = "Gonzalez",
                            PhoneNumber = "(555) 901-2345",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 50,
                            Address = "202 Pine St, Smalltown, USA",
                            Email = "jason.taylor@example.com",
                            FirstName = "Jason",
                            LastName = "Taylor",
                            PhoneNumber = "(555) 012-3456",
                            isActive = true
                        });
                });

            modelBuilder.Entity("BurgerAppDomain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 43,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 46,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 18,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 11,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 20,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 19,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 7,
                            CustomerId = 24,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 8,
                            CustomerId = 30,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 9,
                            CustomerId = 12,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 10,
                            CustomerId = 29,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 11,
                            CustomerId = 21,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 12,
                            CustomerId = 42,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 13,
                            CustomerId = 11,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 14,
                            CustomerId = 13,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 15,
                            CustomerId = 34,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 16,
                            CustomerId = 39,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 17,
                            CustomerId = 23,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 18,
                            CustomerId = 33,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 19,
                            CustomerId = 14,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 20,
                            CustomerId = 7,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 21,
                            CustomerId = 36,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 22,
                            CustomerId = 13,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 23,
                            CustomerId = 43,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 24,
                            CustomerId = 39,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 25,
                            CustomerId = 6,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 26,
                            CustomerId = 29,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 27,
                            CustomerId = 39,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 28,
                            CustomerId = 37,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 29,
                            CustomerId = 19,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 30,
                            CustomerId = 18,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 31,
                            CustomerId = 24,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 32,
                            CustomerId = 10,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 33,
                            CustomerId = 50,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 34,
                            CustomerId = 27,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 35,
                            CustomerId = 34,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 36,
                            CustomerId = 41,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 37,
                            CustomerId = 14,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 38,
                            CustomerId = 39,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 39,
                            CustomerId = 26,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 40,
                            CustomerId = 10,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 41,
                            CustomerId = 46,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 42,
                            CustomerId = 39,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 43,
                            CustomerId = 20,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 44,
                            CustomerId = 5,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 45,
                            CustomerId = 35,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 46,
                            CustomerId = 37,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 47,
                            CustomerId = 2,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            OrderId = 48,
                            CustomerId = 24,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 49,
                            CustomerId = 24,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        },
                        new
                        {
                            OrderId = 50,
                            CustomerId = 14,
                            OrderDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing"
                        });
                });

            modelBuilder.Entity("BurgerAppDomain.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SizeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BurgerAppDomain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Double Big King Menu. Comes with french fries and coke!",
                            Name = "Double Big King",
                            Stock = 999,
                            UnitPrice = 123
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Texas Smokehouse Menu. Comes with french fries and coke!",
                            Name = "Texas Smokehouse",
                            Stock = 999,
                            UnitPrice = 123
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Whopper Menu. Comes with french fries and coke!",
                            Name = "Whopper",
                            Stock = 999,
                            UnitPrice = 123
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Triple Whopper Menu. Comes with french fries and coke!",
                            Name = "Triple Whopper",
                            Stock = 999,
                            UnitPrice = 123
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "King Beef Menu. Comes with french fries and coke!",
                            Name = "King Beef",
                            Stock = 999,
                            UnitPrice = 123
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Nuggets Menu. Comes with french fries and coke!",
                            Name = "Nuggets",
                            Stock = 999,
                            UnitPrice = 123
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Chicken Tenders Menu. Comes with french fries and coke!",
                            Name = "Chicken Tenders",
                            Stock = 999,
                            UnitPrice = 123
                        });
                });

            modelBuilder.Entity("BurgerAppDomain.Sauce", b =>
                {
                    b.Property<int>("SauceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SauceId"));

                    b.Property<string>("SauceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SauceId");

                    b.ToTable("Sauces");

                    b.HasData(
                        new
                        {
                            SauceId = 1,
                            SauceName = "Ketchup"
                        },
                        new
                        {
                            SauceId = 2,
                            SauceName = "Mayonnaise"
                        },
                        new
                        {
                            SauceId = 3,
                            SauceName = "Mustard"
                        });
                });

            modelBuilder.Entity("BurgerAppDomain.Size", b =>
                {
                    b.Property<string>("SizeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PriceDifference")
                        .HasColumnType("int");

                    b.HasKey("SizeId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeId = "S",
                            PriceDifference = 0
                        },
                        new
                        {
                            SizeId = "M",
                            PriceDifference = 3
                        },
                        new
                        {
                            SizeId = "L",
                            PriceDifference = 5
                        });
                });

            modelBuilder.Entity("OrderDetailSauce", b =>
                {
                    b.Property<int>("OrderDetailsOrderDetailId")
                        .HasColumnType("int");

                    b.Property<int>("SaucesSauceId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailsOrderDetailId", "SaucesSauceId");

                    b.HasIndex("SaucesSauceId");

                    b.ToTable("OrderDetailSauce");
                });

            modelBuilder.Entity("BurgerAppDomain.Order", b =>
                {
                    b.HasOne("BurgerAppDomain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BurgerAppDomain.OrderDetail", b =>
                {
                    b.HasOne("BurgerAppDomain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerAppDomain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerAppDomain.Size", "Size")
                        .WithMany("OrderDetails")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("OrderDetailSauce", b =>
                {
                    b.HasOne("BurgerAppDomain.OrderDetail", null)
                        .WithMany()
                        .HasForeignKey("OrderDetailsOrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerAppDomain.Sauce", null)
                        .WithMany()
                        .HasForeignKey("SaucesSauceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BurgerAppDomain.Size", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
